apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/application-api/config/crd?ref=7a895f1e2fbc5a620bf22aba81dab5ba65509eac
- https://github.com/codeready-toolchain/host-operator/config/crd?ref=826d3d5928fefa0105852bda895d326abefe992d
- ../../base
